CREATE TABLE LOG_METRICS (
	ID				INTEGER			PRIMARY KEY,
	TIME			DATETIME		NOT NULL,
	LOG_TYPE		VARCHAR(10)		NOT NULL,
	USER_IP			VARCHAR(45)		NOT NULL,
	CONTROLLER		VARCHAR(45)		NOT NULL,
	ROUTE			VARCHAR(200)	NULL,
	RESPONSE_TIME	INTEGER			NULL
)
