CREATE TABLE LOG_METRICS (
	ID			INTEGER			PRIMARY KEY AUTO_INCREMENT ,
	TIME			DATETIME		NOT NULL,
	LOG_TYPE		VARCHAR(10)		NOT NULL,
	USER_IP			VARCHAR(45)		NOT NULL,
  USER_IDENT  VARCHAR (35)  NULL,
	CONTROLLER		VARCHAR(250)		NOT NULL,
	ROUTE			VARCHAR(500)		NULL,
	RESPONSE_TIME		INTEGER			NULL
)
